"""Criando tabela de vacinas 2

Revision ID: 1c679fffe452
Revises: 0526692ab24c
Create Date: 2021-11-22 18:51:32.075226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c679fffe452'
down_revision = '0526692ab24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccine_cards', sa.Column('name', sa.String(), nullable=False))
    op.add_column('vaccine_cards', sa.Column('first_shot_date', sa.DateTime(), nullable=True))
    op.add_column('vaccine_cards', sa.Column('second_shot_date', sa.DateTime(), nullable=True))
    op.add_column('vaccine_cards', sa.Column('vaccine_name', sa.String(), nullable=False))
    op.add_column('vaccine_cards', sa.Column('health_unit_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccine_cards', 'health_unit_name')
    op.drop_column('vaccine_cards', 'vaccine_name')
    op.drop_column('vaccine_cards', 'second_shot_date')
    op.drop_column('vaccine_cards', 'first_shot_date')
    op.drop_column('vaccine_cards', 'name')
    # ### end Alembic commands ###
